### ISSUE TITLE
链表删除常规解法中可能会存在问题

### ISSUE THREAD

**Issue by bigrotor187** [haiyusun/coding-interviews#1]
```java
/**
     * 常规方法，从first开始找到要删除结点的前一个结点，时间复杂度为O(n)
     */
    public void deleteNode_2(Node first, Node toBeDel) {
        if (first == null || toBeDel == null) {
            return;
        }
        // 要删除的就是链表头，它没有前一个结点
        if (first == toBeDel) {
            first = first.next;
        } else {
            Node cur = first;
          	// 找到被删除结点的前一个结点
            while (cur.next != toBeDel) {
                cur = cur.next;
            }
            // cur为toBeDel的前一个结点
            cur.next = cur.next.next;
        }
    }
```

老哥你好，第 18 题删除链表的节点中，上述代码的 `else` 语句块的 `while`循环中，找到被删除结点的前一个结点这个我觉得可能会出现问题，没有中断条件的话，如果要删除的节点不在链表中会一直循环。我觉得应该要加一个中断条件，如果要删除节点不在链表中，并且已经遍历完了链表要退出循环。修改如下：
```java
/**
     * 常规方法，从first开始找到要删除结点的前一个结点，时间复杂度为O(n)
     */
    public void deleteNode_2(Node first, Node toBeDel) {
        if (first == null || toBeDel == null) {
            return;
        }
        // 要删除的就是链表头，它没有前一个结点
        if (first == toBeDel) {
            first = first.next;
        } else {
            Node cur = first;
          	// 找到被删除结点的前一个结点
            while (curr.next != null && cur.next != toBeDel) {
                cur = cur.next;
            }
            if (curr.next == null) {
                return;
            }
            // cur为toBeDel的前一个结点
            cur.next = cur.next.next;
        }
    }
```
希望老哥看下这样可不可行，谢谢。

**Comment by carpeventus** [comment]
> ```java
> /**
>      * 常规方法，从first开始找到要删除结点的前一个结点，时间复杂度为O(n)
>      */
>     public void deleteNode_2(Node first, Node toBeDel) {
>         if (first == null || toBeDel == null) {
>             return;
>         }
>         // 要删除的就是链表头，它没有前一个结点
>         if (first == toBeDel) {
>             first = first.next;
>         } else {
>             Node cur = first;
>           	// 找到被删除结点的前一个结点
>             while (cur.next != toBeDel) {
>                 cur = cur.next;
>             }
>             // cur为toBeDel的前一个结点
>             cur.next = cur.next.next;
>         }
>     }
> ```
> 
> 老哥你好，第 18 题删除链表的节点中，上述代码的 `else` 语句块的 `while`循环中，找到被删除结点的前一个结点这个我觉得可能会出现问题，没有中断条件的话，如果要删除的节点不在链表中会一直循环。我觉得应该要加一个中断条件，如果要删除节点不在链表中，并且已经遍历完了链表要退出循环。修改如下：
> 
> ```java
> /**
>      * 常规方法，从first开始找到要删除结点的前一个结点，时间复杂度为O(n)
>      */
>     public void deleteNode_2(Node first, Node toBeDel) {
>         if (first == null || toBeDel == null) {
>             return;
>         }
>         // 要删除的就是链表头，它没有前一个结点
>         if (first == toBeDel) {
>             first = first.next;
>         } else {
>             Node cur = first;
>           	// 找到被删除结点的前一个结点
>             while (curr.next != null && cur.next != toBeDel) {
>                 cur = cur.next;
>             }
>             if (curr.next == null) {
>                 return;
>             }
>             // cur为toBeDel的前一个结点
>             cur.next = cur.next.next;
>         }
>     }
> ```
> 
> 希望老哥看下这样可不可行，谢谢。

已经修改
